# Generated by Django 5.2.11 on 2026-02-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('status', models.CharField(choices=[('actif', 'actif'), ('suppr', 'suppr'), ('pending', 'pending')], default='pending', max_length=16)),
                ('comment', models.TextField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.patient')),
            ],
        ),
    ]
